# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-29 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SomeTable',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False, unique=True)),
                ('column1', models.TextField(blank=True, null=True)),
                ('column2', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
