# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-31 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Table', '0003_auto_20180530_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='sometable',
            name='column4',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Столбик4'),
        ),
        migrations.AlterField(
            model_name='sometable',
            name='column1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Столбик1'),
        ),
        migrations.AlterField(
            model_name='sometable',
            name='column2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Столбик2'),
        ),
        migrations.AlterField(
            model_name='sometable',
            name='column3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Столбик3'),
        ),
        migrations.AlterField(
            model_name='sometable',
            name='id',
            field=models.IntegerField(blank=True, primary_key=True, serialize=False, unique=True, verbose_name=''),
        ),
    ]
