# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-31 16:01
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Table', '0004_auto_20180531_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sometable',
            name='column1',
        ),
        migrations.RemoveField(
            model_name='sometable',
            name='column2',
        ),
        migrations.RemoveField(
            model_name='sometable',
            name='column3',
        ),
        migrations.RemoveField(
            model_name='sometable',
            name='column4',
        ),
        migrations.AddField(
            model_name='sometable',
            name='data',
            field=jsonfield.fields.JSONField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sometable',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name=''),
        ),
    ]
