# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-31 16:04
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Table', '0005_auto_20180531_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sometable',
            name='data',
            field=jsonfield.fields.JSONField(default={}),
        ),
    ]
