# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-31 18:04
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Table', '0008_auto_20180531_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jsontable',
            name='string',
        ),
        migrations.AddField(
            model_name='jsontable',
            name='data',
            field=jsonfield.fields.JSONField(default={'column1': '', 'column2': ''}),
        ),
    ]
